[2024-05-17T20:40:34.769+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T20:40:34.809+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T20:40:34.824+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T20:40:34.829+0000] {taskinstance.py:2306} INFO - Starting attempt 9 of 9
[2024-05-17T20:40:34.852+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_based_on_validation> on 2024-05-17 12:31:17.083416+00:00
[2024-05-17T20:40:34.867+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10339) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T20:40:34.870+0000] {standard_task_runner.py:63} INFO - Started process 10351 to run task
[2024-05-17T20:40:34.869+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'branch_based_on_validation', 'manual__2024-05-17T12:31:17.083416+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmpqq60yk85']
[2024-05-17T20:40:34.871+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask branch_based_on_validation
[2024-05-17T20:40:34.945+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation manual__2024-05-17T12:31:17.083416+00:00 [running]> on host e512d0910ba5
[2024-05-17T20:40:35.080+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='branch_based_on_validation' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T12:31:17.083416+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T12:31:17.083416+00:00'
[2024-05-17T20:40:35.081+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T20:40:35.098+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-17T20:40:35.113+0000] {python.py:237} INFO - Done. Returned value was: ['save_file']
[2024-05-17T20:40:35.114+0000] {branch.py:36} INFO - Branch into ['save_file']
[2024-05-17T20:40:35.115+0000] {skipmixin.py:178} INFO - Following branch ['save_file']
[2024-05-17T20:40:35.129+0000] {skipmixin.py:246} INFO - Skipping tasks []
[2024-05-17T20:40:35.144+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T20:40:35.170+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_ingestion_pipelines_2, task_id=branch_based_on_validation, run_id=manual__2024-05-17T12:31:17.083416+00:00, execution_date=20240517T123117, start_date=20240517T204034, end_date=20240517T204035
[2024-05-17T20:40:35.206+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-17T20:40:35.240+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-17T20:40:35.244+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
