[2024-05-17T20:38:15.916+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T20:38:15.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T20:38:15.973+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T20:38:15.975+0000] {taskinstance.py:2306} INFO - Starting attempt 8 of 8
[2024-05-17T20:38:15.994+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_based_on_validation> on 2024-05-17 12:31:17.083416+00:00
[2024-05-17T20:38:16.008+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10160) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T20:38:16.010+0000] {standard_task_runner.py:63} INFO - Started process 10170 to run task
[2024-05-17T20:38:16.010+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'branch_based_on_validation', 'manual__2024-05-17T12:31:17.083416+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmp1_took83']
[2024-05-17T20:38:16.012+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask branch_based_on_validation
[2024-05-17T20:38:16.077+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation manual__2024-05-17T12:31:17.083416+00:00 [running]> on host e512d0910ba5
[2024-05-17T20:38:16.194+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='branch_based_on_validation' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T12:31:17.083416+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T12:31:17.083416+00:00'
[2024-05-17T20:38:16.195+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T20:38:16.213+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-17T20:38:16.228+0000] {python.py:237} INFO - Done. Returned value was: ['save_file']
[2024-05-17T20:38:16.230+0000] {branch.py:36} INFO - Branch into ['save_file']
[2024-05-17T20:38:16.231+0000] {skipmixin.py:178} INFO - Following branch ['save_file']
[2024-05-17T20:38:16.244+0000] {skipmixin.py:246} INFO - Skipping tasks []
[2024-05-17T20:38:16.266+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T20:38:16.290+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_ingestion_pipelines_2, task_id=branch_based_on_validation, run_id=manual__2024-05-17T12:31:17.083416+00:00, execution_date=20240517T123117, start_date=20240517T203815, end_date=20240517T203816
[2024-05-17T20:38:16.348+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-17T20:38:16.386+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-17T20:38:16.389+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
